### ISSUE TITLE
"integer" type should allow for arbitrarily large integers

### ISSUE THREAD

**Issue by aoberoi** [johnstevenson/json-works#1]
First of all, thanks so much for this library.

I'm running into an issue while validating against a Schema where a property is declared of type `integer`, but on Windows and any other 32bit OS the validation is failing because the integer in the data is very large.

The [JSON Schema spec](http://json-schema.org/latest/json-schema-validation.html#anchor5) says: "The JSON specification does not define any bounds to the scale or precision of numeric values...." . Because of the limitations of the `integer` type in PHP, the number in my data is [actually being stored](http://php.net/manual/en/language.types.integer.php#language.types.integer.overflow) as a "float" (which, if you ask `gettype()`, is a "double").

Therefore I believe we have a bug in the library for validating against arbitrarily large integers. I have a test case where I can show this failure. I'll be sending a PR with that code.

**Comment by aoberoi** [comment]
PING

**Comment by johnstevenson** [comment]
@aoberoi. Many thanks for the fix and sorry for ignoring this issue for so long and my apologies for making you have to fork it yourself in order to apply the fix.

I really haven't got any excuses, other than to say that this library will be better maintained in future.

I see that you are using the library for validation. At [line #153](https://github.com/opentok/OpenTok-PHP-SDK/blob/master/src/OpenTok/Util/Validators.php#L153) you don't actually need to encode+decode your array data: `$document->loadData($archiveData);` will work just fine.
